Feature/documents mobile
labhackercd/new-wikilegis pull request #55
Opened 2019-01-22 15:02 UTC by Pettalves

2019-01-22 16:07 UTC, cfviotti commented on src/static/scss/components/_document-body.scss
> +      margin-left: 0;
I also would suggest maybe removing this right padding along with the left padding on the sidebar wrapper, and resorting only to the outer document padding itself for spacing. A bit more simpler that way

2019-01-22 16:11 UTC, cfviotti requested changes
- The sidebar (which really isn't a "side"bar, maybe renaming that to something more generic would be nice) does not extend its height fully when on mobile
![image](https://user-images.githubusercontent.com/6797129/51546605-a9b36e80-1e4b-11e9-812b-2cb07d6e9d9f.png)

- It also wont close itself when you resize your window back to a wider width.
I would suggest solving this by styling the sidebar itself to become somewhat like a modal on mobile, instead of duplicating its content in the markup. It should be possible.
![image](https://user-images.githubusercontent.com/6797129/51547398-580be380-1e4d-11e9-8f62-20b335b8dfd8.png)

- The close button is not doing anything right now.

- Right before the mobile breakpoint the content seems too constricted. I guess adjusting the tablet breakpoint with narrower paddings would suffice.
![image](https://user-images.githubusercontent.com/6797129/51548556-b76af300-1e4f-11e9-9dc8-56c0dd4c3f00.png)

- Lastly please make sure all tests are passing

2019-01-24 16:16 UTC, Pettalves commented on src/static/scss/components/_document-body.scss
> +      margin-left: 0;
Fixed

2019-01-24 16:31 UTC, Pettalves commented
> * The sidebar (which really isn't a "side"bar, maybe renaming that to something more generic would be nice) does not extend its height fully when on mobile
>   ![image](https://user-images.githubusercontent.com/6797129/51546605-a9b36e80-1e4b-11e9-812b-2cb07d6e9d9f.png)
> * It also wont close itself when you resize your window back to a wider width.
>   I would suggest solving this by styling the sidebar itself to become somewhat like a modal on mobile, instead of duplicating its content in the markup. It should be possible.
>   ![image](https://user-images.githubusercontent.com/6797129/51547398-580be380-1e4d-11e9-8f62-20b335b8dfd8.png)
> * The close button is not doing anything right now.
> * Right before the mobile breakpoint the content seems too constricted. I guess adjusting the tablet breakpoint with narrower paddings would suffice.
>   ![image](https://user-images.githubusercontent.com/6797129/51548556-b76af300-1e4f-11e9-9dc8-56c0dd4c3f00.png)
> * Lastly please make sure all tests are passing

Fixed

2019-01-24 17:53 UTC, cfviotti requested changes
- Please make sure the document text is centralized when on a table breakpoint. It looks odd.
![image](https://user-images.githubusercontent.com/6797129/51697276-955ba700-1fee-11e9-826b-0479bf62e9b0.png)

- Remove this margin as it makes the document text uncentered on mobile
![image](https://user-images.githubusercontent.com/6797129/51697471-056a2d00-1fef-11e9-9f4b-ba4287bfe0be.png)

- Make sure the body has its scroll locked when the modal is open
![image](https://user-images.githubusercontent.com/6797129/51697738-b670c780-1fef-11e9-8273-3ca0b345d620.png)

2019-01-25 14:10 UTC, cfviotti approved these changes

2019-01-25 14:14 UTC, merged