Feature/onboarding modal
labhackercd/new-wikilegis pull request #60
Opened 2019-01-25 15:56 UTC by cfviotti

This PR creates the feature of opening a modal specific for the onboardings.

The opinion onboarding should open when the logged user first opens a project. It should never appear again after clicking its button.

The text selection onboarding should open after passing through all available opinions and never appear again after clicking its button.

2019-01-25 19:35 UTC, Pettalves commented on src/static/scss/components/_app-modal.scss
> +    animation: fade-in-bottom 1s 4s $swift-out forwards;
I would take the animation and the delay out of the user experience.

2019-01-25 19:35 UTC, Pettalves commented on src/static/scss/components/_app-modal.scss
> +      max-width: 55rem;
Maybe it's better to follow something like the document page (document-body.scss): max-width: 66ch.
Make reading easier 🤘

2019-01-29 12:41 UTC, msfernandes requested changes
When there's no opinion card the opinion onboarding is still opening and the text selection onboarding does not open. Is this correct?

2019-01-31 20:33 UTC, cfviotti commented
Please check if everything is on point now!

2019-02-04 17:47 UTC, msfernandes requested changes

2019-02-04 17:47 UTC, msfernandes commented on src/static/js/components/opinionOnboarding/view.js
> +      }
If there is no opinion cards, should not trigger `events.showTextSelectionOnboarding`?

2019-02-04 17:47 UTC, msfernandes commented on src/static/js/components/opinionOnboarding/view.js
> +      events.showOpinionOnboarding.publish();
Isn't better publish this event only if there is opinionCards?

2019-02-06 12:23 UTC, merged