Feature/undo suggestion
labhackercd/new-wikilegis pull request #75
Opened 2019-02-14 18:53 UTC by msfernandes

2019-02-14 19:59 UTC, cfviotti requested changes
Whenever I send a suggestion after another one, the behavior of the alert message seems erratic.
If I do this quick enough, the progress-bar has already been filled and the second suggestion is sent almost immediately, with no time to cancel it.

The circled-arrow icon seems way too small. If you rebase this branch with `dev`, the icon mixin has been updated to allow for an explicit size set as a parameter. You may fiddle with that!

2019-02-15 12:03 UTC, msfernandes commented
> Whenever I send a suggestion after another one, the behavior of the alert message seems erratic.
If I do this quick enough, the progress-bar has already been filled and the second suggestion is sent almost immediately, with no time to cancel it.

I know it! But as this bugs is not related to this PR I'll open a new branch to fix it :)

> The circled-arrow icon seems way too small. If you rebase this branch with `dev`, the icon mixin has been updated to allow for an explicit size set as a parameter. You may fiddle with that!

Ok!

2019-02-15 12:18 UTC, msfernandes commented
@cfviotti I updated the icon size:
![image](https://user-images.githubusercontent.com/2891076/52856226-fd437000-310a-11e9-89d4-a162bf384875.png)

2019-02-15 12:23 UTC, erivanio approved these changes

2019-02-15 13:26 UTC, cfviotti approved these changes

2019-02-15 13:36 UTC, merged